#!/bin/bash

dir=$1
RESULT=`ls -a $dir | sort`
IFS=$'\n'
declare -a FILEARRAY
let count=0

for DOT in $RESULT
do
  if [ ! -r "$dir/$DOT" ] 
  then
        continue
  fi 
  if [[ ! -L "$dir/$FILE" && -r "$dir/$FILE" ]]
  then
     if [ -f "$dir/$DOT" ]
     then 
        if [ "${DOT:0:1}"=="." ]
        then 
               FILEARRAY[$count]="$dir/$DOT"
               let count=count+1
       fi
  else 
       continue
  fi
fi
done
     
for FILE in $RESULT
do  
  if [ ! -r "$dir/$FILE" ]
  then 
      continue
  fi
  if [ ! -L "$dir/$FILE" ]
  then 
    continue 
  fi
  if [ -f "$dir/$File" ]
  then
  FILEARRAY[$count]="$dir/$File"
  let count=$count+1
  else
   continue
  fi
done

for ((i=0;i<$count;i++))
do 
  for ((j=$i+1;j<$count;j++))
  do 
    cmp -s "${FILEARRAY[$i]}" "${FILEARRAY[$j]}"
    if [ $? -eq 0 ]
    then
        ln -f -P  "${FILEARRAY[$i]}" "${FILEARRAY[$j]}" 
    fi
  done
done
  
      

